/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types.js"
import type {  BusySlot,  CalendarExtraction,  Confidence,  DayAvailability } from "./types.js"
import type * as types from "./types.js"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface BusySlot {
      start?: string | null
      end?: string | null
      title?: string | null
      durationMinutes?: number | null
    }
    export interface CalendarExtraction {
      isWeekView?: boolean | null
      date?: string | null
      weekStart?: string | null
      busySlots: BusySlot[]
      days: DayAvailability[]
      needsDateConfirmation?: boolean | null
      confidence?: types.Confidence | null
    }
    export interface DayAvailability {
      date?: string | null
      busySlots: BusySlot[]
      confidence?: types.Confidence | null
    }
}